### PR TITLE
Create initial README

### PR DESCRIPTION
**Pull request by arturkot**

### CODE REVIEW

**Comment by arturkot** [comment]
Hi guys,

here goes initial README. Any suggestions?

**Comment by jakub300** [comment]
Could you add at least a sentence of text to each step (Installation, usage)? It is also worth mentioning that one hast to add their own prettier config.

**Review by luboskmetko — APPROVED** [review]

**Comment by arturkot** [comment]
@jakub300 Updated the readme!

**Review by jakub300 — APPROVED** [review]
Much better.
I would put command with \``` to be the same, full highlight as others. Also I would remove word "simply".

**Comment by arturkot** [comment]
Done!

**Comment by jakub300** [comment]
Great

**Pull request merged**
